### ISSUE TITLE
Preprocessing of the Dataset

### ISSUE THREAD

**Issue by VIROBO-15** [funkelab/linajea#57]
Hi,
I found your paper very interesting.
Can you please provide the preprocess of the datasets

**Comment by abred** [comment]
Hi @VIROBO-15 ,
if I understand you correctly, you would like to know how we preprocessed the data?
We did not do much, we just took the data as provided by their respective publications, and normalized it to the range [0,1].

**Comment by abred** [comment]
Please let us know if you have any further questions.
